spring.application.name=todo-app
spring.datasource.url=jdbc:postgresql://localhost:5432/tododb
spring.datasource.username=postgres
spring.datasource.password=postgres
debug=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
